version: '3'

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  api:
    container_name: kyo-backend-yoda
    build:
      context: ./
    image: kyo-backend-yoda
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
volumes:
  db:
    driver: local
